<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa7010a1068656c6c6f776f726c642e70726f746f12046772706322200a" .
            "0c48656c6c6f5265717565737412100a086772656574696e671801200128" .
            "09221e0a0d48656c6c6f526573706f6e7365120d0a057265706c79180120" .
            "01280932430a0c48656c6c6f5365727669636512330a0853617948656c6c" .
            "6f12122e677270632e48656c6c6f526571756573741a132e677270632e48" .
            "656c6c6f526573706f6e7365620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

