<?php

require './vendor/autoload.php';
require './Demo.php';
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-11-22 at 13:10:15.
 */
class DemoTest extends TestCase
{
    /**
     * @var Demo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Demo;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Demo::dd
     * @todo   Implement testDd().
     */
    public function testDd()
    {
        // Remove the following lines when you implement this test.
        $this->assertTrue(true);
    }
}
