<?php

$str="{
    \"ack\": true,
    \"msg\": \"获取定价信息成功\",
    \"code\": null,
    \"data\": {
        \"success_list\": [
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"25.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"18.89\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"18.89\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"23.99\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"20.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"21.39\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"20.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"20.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"20.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"18.89\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"23.99\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"20.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"18.89\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"23.99\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"23.99\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"23.99\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"20.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"20.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"25.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"23.99\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"18.89\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"20.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"23.99\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"18.89\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"25.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"21.39\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"20.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"25.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"20.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"20.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"21.39\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"25.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"18.89\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"25.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"23.99\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"20.19\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            },
            {
                \"product_id\": 53015041,
                \"msrp\": \"22.69\",
                \"total_price\": \"7.99\",
                \"product_total_weight\": \"215.00\",
                \"discount_price\": \"7.99\",
                \"shipping_method\": \"12\",
                \"shipping_category\": 1,
                \"shipping_costs\": \"4.59\",
                \"price_info\": {
                    \"csc_id\": \"32\",
                    \"channel\": \"mallmy\",
                    \"site_code\": \"mallmy.com1\",
                    \"commission\": \"15.00\",
                    \"gross_margin\": \"25.00\",
                    \"reg_gross_margin\": \"0.00\",
                    \"parcel_processing_fee\": \"2.00\",
                    \"vat_tax_rate\": \"0.00\",
                    \"currency_code\": \"USD\",
                    \"country_code\": \"RU\",
                    \"update_time\": \"2018-08-01 14:37:19\",
                    \"is_open_smart_gross_margin\": \"N\",
                    \"is_open_list_price\": \"N\",
                    \"list_price_multiple\": \"1.00\",
                    \"currency_rate\": \"6.6666\"
                },
                \"base_price\": \"4.29\",
                \"output_price_type\": 1
            }
        ],
        \"fail_list\": [
            {
                \"product_id\": null,
                \"msg\": \"传入价格类型为空\"
            }
        ]
    }
}";
$js= json_decode($str,true);
echo '<pre>';
print_r($js);