version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.3.0
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=elasticsearch   #集群名称为elasticsearch
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #jvm内存分配为512MB
      - "discovery.type=single-node" #单节点启动
      - "TZ=Asia/Shanghai"
    volumes:
      - /var/docker/elasticsearch/data:/usr/share/elasticsearch/data
      - /var/docker/elasticsearch/logs:/usr/share/elasticsearch/logs
      - /var/docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /etc/localtime:/etc/localtime
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:7.3.0
    container_name: kibana
    restart: always
    links:
      - elasticsearch:es  #配置elasticsearch域名为es
    depends_on:
      - elasticsearch
    volumes:
      - /var/docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /var/docker/kibana/data:/usr/share/kibana/data
      - /etc/localtime:/etc/localtime
    ports:
      - 5601:5601
  logstash:
    image: logstash:7.3.0
    container_name: logstash
    restart: always
    volumes:
      - /var/docker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - /etc/localtime:/etc/localtime
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:es #配置elasticsearch域名为es
    ports:
      - 5044:5044