<?php
require_once __DIR__ . '/../vendor/autoload.php';

use App\Test;

use PHPUnit\Framework\TestCase;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-11-22 at 13:44:04.
 */
class TestTest extends TestCase
{
    /**
     * @var Test
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Test;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Test::dd
     * @todo   Implement testDd().
     */
    public function testDd()
    {  print_r($this->object);

        $this->assertTrue($this->object->dd(1,2)>0);
    }
}
